permalink: "/:year/:month/:day/:title.html"
name: "Eston"
subtitle: "A simple theme."
root: "/jekyll-theme-eston"

# Build settings
baseurl: "/jekyll-theme-eston/" # Change this to your relative path (ex: /blog/), or leave just a /
# 分页
paginate: 5
paginate_path: "page:num"

# Plugins
gems:
  - jekyll-paginate

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

author: "cyw"
disqus: "rose1988c"
google: "UA-98154695-1"

navigations:
  - title: "Archive"
    class: "fa fa-list-ul"
    href: "pages/archive.html"
  - title: "Tags"
    class: "fa fa-tags"
    href: "pages/tags.html"